[package]
name = "chapter2"
version = "0.1.0"
edition = "2021"

[dependencies]
winit.workspace = true
wgpu.workspace = true
pollster.workspace = true
glam = "0.30"
egui = { version = "0.31" }
egui-wgpu = "0.31"
egui-winit = "0.31"
bytemuck = "1.22.0"